### ISSUE TITLE
Feature Request: brief inline documentation

### ISSUE THREAD

**Issue by jbflot** [cmroboticsacademy/fire-engine#1]
Add short bits of text to explain fields so that our interns (and future open source users) know what they mean

**Comment by bynarlogic** [comment]
@vnguyen13 Do you want to document all of the quiz settings so that Tom can write inline documentation? 

@luong-thomas I think this can be handled with either tooltips or labels.

**Comment by vnguyen13** [comment]
@bynarlogic SURE!

@luong-thomas 
**Questions:**
1. Question: The question that you are asking. This is a string. 
2. Question Type: The type of question you are asking. The choices are available in the dropdown. 
3. Points: The number of points that the question is worth. This can be any real number. The number of points for all questions in a quiz is accumulated to give a percentage score. 

**Answers:**
1. Content: An answer to the question. This is a string. 
2. Weight: The weight of the question compared to the other questions in a quiz. This can be any real number. For each question, we multiply the weight by the points and then sum the total earned points.

**Quizzes:**
1. Name: The name of the quiz. This is a string. 
2. Description: A description of the quiz. 
3. Attempts allowed: The total number of attempts that a user is allowed for the quiz. 
4. Questions per page: The number of questions that will be listed per page in the quiz.
5. Randomize Questions: Randomize the question order that the student sees in the quiz. 
6. Auto Submit: If this setting is enabled, the quiz attempt will automatically submit the quiz attempt once the time limit has been exceeded. 
7. Time Window: The dates that the quiz is available. You can set a time open and a time close. 
8. Time Limit: Enabling this setting will look at the time limit minutes and will only allow the user to have that amount of time to take the quiz attempt. 
9. Time Limit Minutes: The number of minutes a user has to make a quiz attempt. This is used only if the Time Limit setting is enabled. 

@bynarlogic Sanity check me

**Comment by bynarlogic** [comment]
@vnguyen13  Looks good. @luong-thomas Let's add this documentation to the quiz form as you see fit. Thanks!

**Comment by bynarlogic** [comment]
Created Question Tooltip for each field.
