### ISSUE TITLE
Feature request: Number of attempts, time limit notifcations

### ISSUE THREAD

**Issue by luong-thomas** [cmroboticsacademy/fire-engine#10]
Displaying a number of attempts allowed per quiz, and if the quiz was under a time-limit, or an auto-submission. What does it look like if the user have taken up all of their attempts and still did not pass? What does it look like taking a quiz with a time limit? What does auto-submission do?

**Comment by bynarlogic** [comment]
None of these features are currently used in CS2N. We will expand the API to communicate time-limit and auto submission at a later time.
