### ISSUE TITLE
Feature request: Page number / Total page number

### ISSUE THREAD

**Issue by luong-thomas** [cmroboticsacademy/fire-engine#11]
Nice to have a small page number progress, or some sort of progress while taking the quiz.

**Comment by bynarlogic** [comment]
@luong-thomas We can implement that on the front end. The response from FireEngine's [API](https://cs-stem-network.postman.co/collections/1945713-45140974-1067-471f-9455-f6868252bf8d?workspace=485e7e97-8a9a-49c0-8882-f9021e457f56) for the quiz edit page should give you the current page number.

**Comment by bynarlogic** [comment]
Done. 
<img width="1114" alt="screen shot 2018-05-24 at 2 12 13 pm" src="https://user-images.githubusercontent.com/6131539/40503561-7e598be2-5f5c-11e8-9304-bc5fb3039c09.png">
