### ISSUE TITLE
Error: Get 404'd when checking members progress page for quiz scores

### ISSUE THREAD

**Issue by luong-thomas** [cmroboticsacademy/fire-engine#12]
Added activity with new fire engine quiz, tried to check score, get 404

**Comment by bynarlogic** [comment]
Nice Catch. We need to account for requirement type quiz_engine in the mapped badge progress page.

**Comment by bynarlogic** [comment]
This was a CS2N issue. Mapped Badge Progress has been updated to handle quiz_engine requirements.
