### ISSUE TITLE
Bug: Server error when quiz attempts are used up

### ISSUE THREAD

**Issue by luong-thomas** [cmroboticsacademy/fire-engine#15]
Quiz attempts are working. However, it renders an internal server error page on CS2N:

757: unexpected token at 'Internal server error

**Comment by bynarlogic** [comment]
Implemented a -1 wildcard setting to allow for an infinite amount of attempts. Added response to POST api/v1/user_attempts that returns an 'attempts exceeded' message if the number of attempts has been exceeded.
