### ISSUE TITLE
Feature request: Allow Fire Engine Admin to delete specified user quiz attempts

### ISSUE THREAD

**Issue by luong-thomas** [cmroboticsacademy/fire-engine#16]
Probably more on the CS2N side, but it would be nice to have a reset number of attempts, but save the number of attempts made data.

**Comment by bynarlogic** [comment]
I'm not sure I understand this request or the business case for it.

**Comment by vnguyen13** [comment]
Clarified the title.

**Comment by bynarlogic** [comment]
Created user attempts page with search capabilities. Attempts can be deleted.
